Repository EPFL-SwEnt-2024-LaStartUp/TripTracker, pull requests merged in 2024-05, with the labels that each got.

#135 Smoothing maps and record
  app/src/androidTest/java/com/example/triptracker/map/AddSpotTest.kt
  app/src/androidTest/java/com/example/triptracker/map/MapOverviewTest.kt
  app/src/androidTest/java/com/example/triptracker/map/MapPopupTest.kt
  app/src/main/java/com/example/triptracker/MainActivity.kt
  app/src/main/java/com/example/triptracker/model/geocoder/NominatimApi.kt
  app/src/main/java/com/example/triptracker/view/Navigation.kt
  app/src/main/java/com/example/triptracker/view/home/HomeScreen.kt
  app/src/main/java/com/example/triptracker/view/map/AddSpot.kt
  app/src/main/java/com/example/triptracker/view/map/MapOverview.kt
  app/src/main/java/com/example/triptracker/view/map/MapPopups.kt
  app/src/main/java/com/example/triptracker/view/map/RecordScreen.kt
  app/src/main/java/com/example/triptracker/viewmodel/MapViewModel.kt
Labels: 8H

#147 Link the User Profile Edit Screen
  app/src/androidTest/java/com/example/triptracker/screens/userProfile/UserProfileEditScreenTest.kt
  app/src/main/java/com/example/triptracker/MainActivity.kt
  app/src/main/java/com/example/triptracker/model/repository/ImageRepository.kt
  app/src/main/java/com/example/triptracker/view/Navigation.kt
  app/src/main/java/com/example/triptracker/view/profile/UserProfileEditScreen.kt
  app/src/main/java/com/example/triptracker/view/profile/UserProfileOverview.kt
  app/src/main/java/com/example/triptracker/viewmodel/UserProfileViewModel.kt
Labels: 4H

#151 Create & link UI for User Profile Settings
  app/src/main/java/com/example/triptracker/MainActivity.kt
  app/src/main/java/com/example/triptracker/view/Navigation.kt
  app/src/main/java/com/example/triptracker/view/TopNavigationBar.kt
  app/src/main/java/com/example/triptracker/view/profile/UserProfileEditScreen.kt
  app/src/main/java/com/example/triptracker/view/profile/UserProfileOverview.kt
  app/src/main/java/com/example/triptracker/view/profile/UserProfileSettings.kt
Labels: 4H

#177 Offline mode first version
  app/src/androidTest/java/com/example/triptracker/repository/ImageRepositoryTest.kt
  app/src/main/java/com/example/triptracker/MainActivity.kt
  app/src/main/java/com/example/triptracker/model/network/Connection.kt
  app/src/main/java/com/example/triptracker/model/repository/ImageRepository.kt
  app/src/main/java/com/example/triptracker/view/Navigation.kt
  app/src/main/java/com/example/triptracker/view/NavigationBar.kt
  app/src/main/java/com/example/triptracker/view/OfflineScreen.kt
  app/src/main/java/com/example/triptracker/view/profile/UserProfileEditScreen.kt
  app/src/main/java/com/example/triptracker/viewmodel/RecordViewModel.kt
  app/src/main/java/com/example/triptracker/viewmodel/UserProfileViewModel.kt
Labels: 4H

#188 Addspot update
  app/build.gradle.kts
  app/src/androidTest/java/com/example/triptracker/map/AddSpotCameraTest.kt
  app/src/androidTest/java/com/example/triptracker/map/AddSpotTest.kt
  app/src/androidTest/java/com/example/triptracker/screens/AddSpotScreen.kt
  app/src/androidTest/java/com/example/triptracker/screens/home/HomeTest.kt
  app/src/androidTest/java/com/example/triptracker/screens/home/HomeViewScreen.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/triptracker/MainActivity.kt
  app/src/main/java/com/example/triptracker/view/CameraPermissions.kt
  app/src/main/java/com/example/triptracker/view/LoginScreen.kt
  app/src/main/java/com/example/triptracker/view/home/HomeUtils.kt
  app/src/main/java/com/example/triptracker/view/map/AddSpot.kt
  app/src/main/java/com/example/triptracker/view/map/AddSpotTakePictures.kt
  app/src/main/java/com/example/triptracker/view/map/RecordScreen.kt
  gradle/libs.versions.toml
Labels: 8H

#197 Refactoring of user profile edit screen
  app/src/main/java/com/example/triptracker/view/profile/UserProfileEditScreen.kt
  app/src/main/java/com/example/triptracker/viewmodel/UserProfileViewModel.kt
Labels: 1H

#246 Back button for camera screen
  app/src/androidTest/java/com/example/triptracker/view/NavigationBarTest.kt
  app/src/main/java/com/example/triptracker/view/map/AddSpotTakePictures.kt
Labels: 1H

#249 Add download path for offline usage
  app/build.gradle.kts
  app/src/androidTest/java/com/example/triptracker/itinerary/ItineraryDownloadTest.kt
  app/src/androidTest/java/com/example/triptracker/map/MapPopupTest.kt
  app/src/androidTest/java/com/example/triptracker/userProfile/UserProfileFavouritesTest.kt
  app/src/androidTest/java/com/example/triptracker/view/NavigationTest.kt
  app/src/androidTest/java/com/example/triptracker/view/WaitingScreenTest.kt
  app/src/main/java/com/example/triptracker/model/itinerary/ItineraryDownload.kt
  app/src/main/java/com/example/triptracker/view/Navigation.kt
  app/src/main/java/com/example/triptracker/view/home/HomeUtils.kt
  app/src/main/java/com/example/triptracker/view/map/MapPopups.kt
  app/src/main/java/com/example/triptracker/view/map/RecordScreen.kt
  app/src/main/java/com/example/triptracker/view/profile/UserProfileFavourites.kt
  app/src/main/java/com/example/triptracker/view/profile/UserProfileScreenUtils.kt
  app/src/main/java/com/example/triptracker/viewmodel/HomeViewModel.kt
Labels: 8H

#276 Fix photo not updating 🌺
  app/src/androidTest/java/com/example/triptracker/userProfile/UserProfileEditScreenTest.kt
  app/src/androidTest/java/com/example/triptracker/userProfile/UserProfileViewModelTest.kt
  app/src/main/java/com/example/triptracker/view/profile/UserProfileEditScreen.kt
  app/src/main/java/com/example/triptracker/view/profile/UserProfileOverview.kt
  app/src/main/java/com/example/triptracker/viewmodel/UserProfileViewModel.kt
Labels: bug
