Repository EPFL-SwEnt-2024-LaStartUp/TripTracker, pull requests merged in 2024-04, with the labels that each got.

#73 Bugfix maps screen location permission
  app/src/main/java/com/example/triptracker/MainActivity.kt
  app/src/main/java/com/example/triptracker/navigation/LocationUtils.kt
  app/src/main/java/com/example/triptracker/view/map/MapOverview.kt
  app/src/main/java/com/example/triptracker/view/map/RecordScreen.kt
Labels: 2H

#88 Add new spot to path
  app/build.gradle.kts
  app/src/androidTest/java/com/example/triptracker/map/AddSpotTest.kt
  app/src/androidTest/java/com/example/triptracker/screens/AddSpotScreen.kt
  app/src/main/java/com/example/triptracker/model/geocoder/NominatimApi.kt
  app/src/main/java/com/example/triptracker/navigation/LocationUtils.kt
  app/src/main/java/com/example/triptracker/view/map/AddSpot.kt
  app/src/main/java/com/example/triptracker/viewmodel/MapViewModel.kt
  app/src/main/java/com/example/triptracker/viewmodel/RecordViewModel.kt
  app/src/test/java/com/example/triptracker/NominatimGeocoderTest.kt
Labels: 8H

#106 Search Bar Filter Enhancements
  app/src/androidTest/java/com/example/triptracker/screens/home/HomeTest.kt
  app/src/main/java/com/example/triptracker/view/home/HomeScreen.kt
  app/src/main/java/com/example/triptracker/viewmodel/HomeViewModel.kt
Labels: 6H

#131 Few adjustments on UserProfileEditScreen + add 80% test coverage
  app/src/androidTest/java/com/example/triptracker/screens/userProfile/UserProfileEditScreenTest.kt
  app/src/main/java/com/example/triptracker/view/profile/UserProfileEditScreen.kt
Labels: 1H

#130 Change Itinerary and UserProfile data class : Pass user e-mail so that can retrieve full user profile upon Home Screen creation
  app/build.gradle.kts
  app/src/androidTest/java/com/example/triptracker/itinerary/ItineraryListTest.kt
  app/src/androidTest/java/com/example/triptracker/itinerary/ItineraryTest.kt
  app/src/androidTest/java/com/example/triptracker/screens/home/HomeTest.kt
  app/src/androidTest/java/com/example/triptracker/userProfile/UserProfileViewModelTest.kt
  app/src/main/java/com/example/triptracker/model/itinerary/Itinerary.kt
  app/src/main/java/com/example/triptracker/model/repository/ItineraryRepository.kt
  app/src/main/java/com/example/triptracker/model/repository/UserProfileRepository.kt
  app/src/main/java/com/example/triptracker/view/ItineraryPreview.kt
  app/src/main/java/com/example/triptracker/view/WaitingScreen.kt
  app/src/main/java/com/example/triptracker/view/home/HomeScreen.kt
  app/src/main/java/com/example/triptracker/view/home/HomeUtils.kt
  app/src/main/java/com/example/triptracker/view/map/MapPopups.kt
  app/src/main/java/com/example/triptracker/viewmodel/HomeViewModel.kt
  app/src/main/java/com/example/triptracker/viewmodel/UserProfileViewModel.kt
Labels: 6H
